# Generated by Django 5.1.3 on 2024-12-02 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_user_inv_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_inv_code',
            field=models.CharField(max_length=6),
        ),
    ]
